package database

func (db *Database) init() error {
	_, err := db.db.Exec(`
	CREATE TABLE IF NOT EXISTS USERS (
	    ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	    NAME TEXT NOT NULL UNIQUE,
	    PASSWORD TEXT,
	    SCREEN_NAME TEXT NOT NULL,
	    ROLE INTEGER NOT NULL
	);

	CREATE TABLE IF NOT EXISTS TEAMS (
		TEAM INTEGER NOT NULL PRIMARY KEY,
	    NAME TEXT NOT NULL UNIQUE
	);

	CREATE TABLE IF NOT EXISTS GAMES (
	  	ID INTEGER NOT NULL PRIMARY KEY,
	  	
	  	RedTeam1 INTEGER NOT NULL REFERENCES TEAMS,
	  	RedTeam2 INTEGER NOT NULL REFERENCES TEAMS,
	  	BlueTeam1 INTEGER NOT NULL REFERENCES TEAMS,
	  	BlueTeam2 INTEGER NOT NULL REFERENCES TEAMS,
	  	
	  	RedScouter1 INTEGER NOT NULL REFERENCES USERS,
	  	RedScouter2 INTEGER NOT NULL REFERENCES USERS,
	  	BlueScouter1 INTEGER NOT NULL REFERENCES USERS,
	  	BlueScouter2 INTEGER NOT NULL REFERENCES USERS
	);

	CREATE TABLE IF NOT EXISTS FORM_ANSWERS (
		ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
		SCOUTER INTEGER NOT NULL REFERENCES USERS,
		GAME INTEGER NOT NULL REFERENCES GAMES,
		TEAM INTEGER NOT NULL REFERENCES TEAMS,
		Location TEXT NOT NULL,
		
		TEAM_ELEMENT TEXT NOT NULL,
		AUTO_DUCK TEXT NOT NULL,
		AUTO_STORAGE TEXT NOT NULL,
		AUTO_SHIPPING TEXT NOT NULL,
		CUBE_LEVEL INTEGER NOT NULL,
		PARKING TEXT NOT NULL,
		
		STORAGE INTEGER NOT NULL,
		SHIPPING_LOW INTEGER NOT NULL,
		SHIPPING_MID INTEGER NOT NULL,
		SHIPPING_HIGH INTEGER NOT NULL,
		SHARED INTEGER NOT NULL,
		DUCKS INTEGER NOT NULL,
		CAPPING TEXT NOT NULL,
		WORKING TEXT NOT NULL,
		NOTES TEXT NOT NULL
	);
`)
	if err != nil {
		return err
	}

	return nil
}
