package database

func (db *Database) init() error {
	_, err := db.db.Exec(`
	CREATE TABLE IF NOT EXISTS USERS (
	    ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	    NAME TEXT NOT NULL UNIQUE,
	    PASSWORD TEXT,
	    SCREEN_NAME TEXT NOT NULL,
	    ROLE INTEGER NOT NULL
	);

	CREATE TABLE IF NOT EXISTS TEAMS (
		TEAM INTEGER NOT NULL PRIMARY KEY,
	    NAME TEXT NOT NULL UNIQUE
	);

	CREATE TABLE IF NOT EXISTS GAMES (
	  	ID INTEGER NOT NULL PRIMARY KEY,
	  	
	  	RedTeam1 INTEGER NOT NULL REFERENCES TEAMS,
	  	RedTeam2 INTEGER NOT NULL REFERENCES TEAMS,
	  	BlueTeam1 INTEGER NOT NULL REFERENCES TEAMS,
	  	BlueTeam2 INTEGER NOT NULL REFERENCES TEAMS,
	  	
	  	RedScouter1 INTEGER NOT NULL REFERENCES USERS,
	  	RedScouter2 INTEGER NOT NULL REFERENCES USERS,
	  	BlueScouter1 INTEGER NOT NULL REFERENCES USERS,
	  	BlueScouter2 INTEGER NOT NULL REFERENCES USERS
	);
`)
	if err != nil {
		return err
	}

	return nil
}
