package database

func (db *Database) init() error {
	_, err := db.db.Exec(`
	CREATE TABLE IF NOT EXISTS USERS (
	    ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	    NAME TEXT NOT NULL UNIQUE,
	    PASSWORD TEXT,
	    SCREEN_NAME TEXT NOT NULL,
	    ROLE INTEGER NOT NULL
	);

	CREATE TABLE IF NOT EXISTS TEAMS (
		TEAM INTEGER NOT NULL PRIMARY KEY,
	    NAME TEXT NOT NULL UNIQUE,
	    NOTES TEXT NOT NULL DEFAULT('')
	);

	CREATE TABLE IF NOT EXISTS GAMES (
	  	ID INTEGER NOT NULL PRIMARY KEY,
	  	GAME_TYPE TEXT DEFAULT (''),
	  	
	  	RED_TEAM1 INTEGER NOT NULL REFERENCES TEAMS,
	  	RED_TEAM2 INTEGER NOT NULL REFERENCES TEAMS,
	  	BLUE_TEAM1 INTEGER NOT NULL REFERENCES TEAMS,
	  	BLUE_TEAM2 INTEGER NOT NULL REFERENCES TEAMS,
	  	
	  	RED_SCOUTER1 INTEGER REFERENCES USERS,
	  	RED_SCOUTER2 INTEGER REFERENCES USERS,
	  	BLUE_SCOUTER1 INTEGER REFERENCES USERS,
	  	BLUE_SCOUTER2 INTEGER REFERENCES USERS
	);

	CREATE TABLE IF NOT EXISTS FORM_ANSWERS (
		ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
		SCOUTER INTEGER NOT NULL REFERENCES USERS,
		GAME INTEGER NOT NULL REFERENCES GAMES,
		TEAM INTEGER NOT NULL REFERENCES TEAMS,
		Location TEXT NOT NULL,
		
		TEAM_ELEMENT TEXT NOT NULL,
		AUTO_DUCK TEXT NOT NULL,
		AUTO_STORAGE INTEGER NOT NULL,
		AUTO_SHIPPING INTEGER NOT NULL,
		CUBE_LEVEL INTEGER NOT NULL,
		PARKING TEXT NOT NULL,
		
		STORAGE INTEGER NOT NULL,
		SHIPPING_LOW INTEGER NOT NULL,
		SHIPPING_MID INTEGER NOT NULL,
		SHIPPING_HIGH INTEGER NOT NULL,
		SHARED INTEGER NOT NULL,
		DUCKS INTEGER NOT NULL,
		CAPPING TEXT NOT NULL,
		WORKING TEXT NOT NULL,
		NOTES TEXT NOT NULL
	);

	CREATE TABLE IF NOT EXISTS  SUPERVISOR_FORM (
		ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
		SCOUTER INTEGER NOT NULL REFERENCES USERS,
		GAME INTEGER NOT NULL REFERENCES GAMES,
		
		NEAR_RED_INTERFERENCE BOOLEAN NOT NULL,
		NEAR_BLUE_INTERFERENCE BOOLEAN NOT NULL,
		
		RED1_PENALTY TEXT NOT NULL,
		RED1_NOTES TEXT,
		
		RED2_PENALTY TEXT NOT NULL,
		RED2_NOTES TEXT,
		
		BLUE1_PENALTY TEXT NOT NULL,
		BLUE1_NOTES TEXT,
		
		BLUE2_PENALTY TEXT NOT NULL,
		BLUE2_NOTES TEXT
	);
`)
	if err != nil {
		return err
	}

	_, _ = db.db.Exec("INSERT INTO USERS (ID, NAME, SCREEN_NAME, ROLE) VALUES (-1, '', '', -1)")
	return nil
}
